### ISSUE TITLE
Mark Current Redirect Issue

### ISSUE THREAD

**Issue by miklb** [hurricane-response/florence-api#69] opened 2018-10-16 14:24 UTC
From `/shelters/outdated` if you click the "mark current" link, it redirects back to `/shelters`

**Comment by nihonjinrxs** [comment] 2019-01-06 21:49
Seems there's some uncertainty about what the issue is here. @miklb can we either close this out if it's really #notabug or provide some better explanation of what's actually happening and what's expected to happen so that someone can implement a test and a fix?

**Comment by miklb** [comment] 2019-01-07 16:30
Probably can close. I recall the issue but seems it can addressed in a different manner

**Comment by nihonjinrxs** [comment] 2019-01-07 23:55
OK, closing.

**Closed by nihonjinrxs** 2019-01-07 23:55 UTC
Labels: bug, good first issue
